### ISSUE TITLE
Can't compile torrust-tracker

### ISSUE THREAD

**Issue by BabaBooey84** [torrust/torrust-documentation#1]
I can't compile the tracker, what is going wrong?

> Compiling torrust-tracker v2.0.1 (/opt/torrust/torrust-tracker)
     Running `rustc --crate-name torrust_tracker --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto=fat -C metadata=1a8fb3d5516f732f -C extra-filename=-1a8fb3d5516f732f --out-dir /opt/torrust/torrust-tracker/target/release/deps -L dependency=/opt/torrust/torrust-tracker/target/release/deps --extern binascii=/opt/torrust/torrust-tracker/target/release/deps/libbinascii-5d31a53920339921.rlib --extern byteorder=/opt/torrust/torrust-tracker/target/release/deps/libbyteorder-3e1a21ac43ab8bb6.rlib --extern chrono=/opt/torrust/torrust-tracker/target/release/deps/libchrono-ff5ef5174195571a.rlib --extern config=/opt/torrust/torrust-tracker/target/release/deps/libconfig-590b693d0bdcab2f.rlib --extern derive_more=/opt/torrust/torrust-tracker/target/release/deps/libderive_more-4cae2f5072a2a305.so --extern env_logger=/opt/torrust/torrust-tracker/target/release/deps/libenv_logger-5bc7708cd00fc52a.rlib --extern external_ip=/opt/torrust/torrust-tracker/target/release/deps/libexternal_ip-32ce7d5b0db08d5d.rlib --extern fern=/opt/torrust/torrust-tracker/target/release/deps/libfern-a7950ab421c59508.rlib --extern hex=/opt/torrust/torrust-tracker/target/release/deps/libhex-4c1132b0a3bf34b2.rlib --extern log=/opt/torrust/torrust-tracker/target/release/deps/liblog-834c8d8492f99f67.rlib --extern percent_encoding=/opt/torrust/torrust-tracker/target/release/deps/libpercent_encoding-fc98ec1175189693.rlib --extern r2d2=/opt/torrust/torrust-tracker/target/release/deps/libr2d2-3126982ec9aa3dbf.rlib --extern r2d2_sqlite=/opt/torrust/torrust-tracker/target/release/deps/libr2d2_sqlite-d82328e835aa2c67.rlib --extern rand=/opt/torrust/torrust-tracker/target/release/deps/librand-90e43681238465f7.rlib --extern serde=/opt/torrust/torrust-tracker/target/release/deps/libserde-15f1b1238101d8b9.rlib --extern serde_bencode=/opt/torrust/torrust-tracker/target/release/deps/libserde_bencode-f34a269da7fd625b.rlib --extern serde_bytes=/opt/torrust/torrust-tracker/target/release/deps/libserde_bytes-5afcb573d02900a5.rlib --extern serde_json=/opt/torrust/torrust-tracker/target/release/deps/libserde_json-bd7436acc49caaf3.rlib --extern tokio=/opt/torrust/torrust-tracker/target/release/deps/libtokio-390045bcb83033d6.rlib --extern toml=/opt/torrust/torrust-tracker/target/release/deps/libtoml-03088a5e4035a0c2.rlib --extern torrust_tracker=/opt/torrust/torrust-tracker/target/release/deps/libtorrust_tracker-39ff7b8bbc59a697.rlib --extern warp=/opt/torrust/torrust-tracker/target/release/deps/libwarp-94f862ffdd5c89c6.rlib -L native=/opt/torrust/torrust-tracker/target/release/build/ring-fc1f1d4294c9040c/out`
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/opt/torrust/torrust-tracker/target/release/deps/torrust_tracker-1a8fb3d5516f732f.torrust_tracker.5ybqilw0-cgu.7.rcgu.o" "-o" "/opt/torrust/torrust-tracker/target/release/deps/torrust_tracker-1a8fb3d5516f732f" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/opt/torrust/torrust-tracker/target/release/deps" "-L" "/opt/torrust/torrust-tracker/target/release/build/ring-fc1f1d4294c9040c/out" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcGEI7os/libring-4912c2f233fa5bd1.rlib" "-Wl,--start-group" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b0414f7c79a0b9b4.rlib" "-Wl,-Bdynamic" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lsqlite3
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `torrust-tracker`

Caused by:
  process didn't exit successfully: `rustc --crate-name torrust_tracker --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto=fat -C metadata=1a8fb3d5516f732f -C extra-filename=-1a8fb3d5516f732f --out-dir /opt/torrust/torrust-tracker/target/release/deps -L dependency=/opt/torrust/torrust-tracker/target/release/deps --extern binascii=/opt/torrust/torrust-tracker/target/release/deps/libbinascii-5d31a53920339921.rlib --extern byteorder=/opt/torrust/torrust-tracker/target/release/deps/libbyteorder-3e1a21ac43ab8bb6.rlib --extern chrono=/opt/torrust/torrust-tracker/target/release/deps/libchrono-ff5ef5174195571a.rlib --extern config=/opt/torrust/torrust-tracker/target/release/deps/libconfig-590b693d0bdcab2f.rlib --extern derive_more=/opt/torrust/torrust-tracker/target/release/deps/libderive_more-4cae2f5072a2a305.so --extern env_logger=/opt/torrust/torrust-tracker/target/release/deps/libenv_logger-5bc7708cd00fc52a.rlib --extern external_ip=/opt/torrust/torrust-tracker/target/release/deps/libexternal_ip-32ce7d5b0db08d5d.rlib --extern fern=/opt/torrust/torrust-tracker/target/release/deps/libfern-a7950ab421c59508.rlib --extern hex=/opt/torrust/torrust-tracker/target/release/deps/libhex-4c1132b0a3bf34b2.rlib --extern log=/opt/torrust/torrust-tracker/target/release/deps/liblog-834c8d8492f99f67.rlib --extern percent_encoding=/opt/torrust/torrust-tracker/target/release/deps/libpercent_encoding-fc98ec1175189693.rlib --extern r2d2=/opt/torrust/torrust-tracker/target/release/deps/libr2d2-3126982ec9aa3dbf.rlib --extern r2d2_sqlite=/opt/torrust/torrust-tracker/target/release/deps/libr2d2_sqlite-d82328e835aa2c67.rlib --extern rand=/opt/torrust/torrust-tracker/target/release/deps/librand-90e43681238465f7.rlib --extern serde=/opt/torrust/torrust-tracker/target/release/deps/libserde-15f1b1238101d8b9.rlib --extern serde_bencode=/opt/torrust/torrust-tracker/target/release/deps/libserde_bencode-f34a269da7fd625b.rlib --extern serde_bytes=/opt/torrust/torrust-tracker/target/release/deps/libserde_bytes-5afcb573d02900a5.rlib --extern serde_json=/opt/torrust/torrust-tracker/target/release/deps/libserde_json-bd7436acc49caaf3.rlib --extern tokio=/opt/torrust/torrust-tracker/target/release/deps/libtokio-390045bcb83033d6.rlib --extern toml=/opt/torrust/torrust-tracker/target/release/deps/libtoml-03088a5e4035a0c2.rlib --extern torrust_tracker=/opt/torrust/torrust-tracker/target/release/deps/libtorrust_tracker-39ff7b8bbc59a697.rlib --extern warp=/opt/torrust/torrust-tracker/target/release/deps/libwarp-94f862ffdd5c89c6.rlib -L native=/opt/torrust/torrust-tracker/target/release/build/ring-fc1f1d4294c9040c/out` (exit status: 1)

**Comment by mickvandijke** [comment]
Hey @BabaBooey84 ,

The installation instructions missed the installation of a few dependencies, I'm sorry for that! Could you try installing the prerequisites listed in the updated installation instructions: https://torrust.com/installation/#install-prerequisites ?

**Comment by BabaBooey84** [comment]
Thanks a lot @WarmBeer  I got it working 👍 
Linux isn't my strong suit so I'm stuck at the Nginx config. When running the `nginx -t` command I get this:

> nginx: [emerg] cannot load certificate "/etc/nginx/CERT_PATH": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/CERT_PATH','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

I probably missed a step where I either were suppose to import or point to a stored certificate.

**Comment by mickvandijke** [comment]
Great! @BabaBooey84 

You can get an SSL certificate for free using Let's Encrypt, here is a tutorial with Nginx: https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/
